export const PATH = {
  HOME: "/pages/index/index/index",
  LOGIN: "/pages/app/login/index",
  FUNC: "/pages/func/index/index",
  TIMETABLE: "/pages/func/timetable/index",
  TIMETABLE_EDITOR: "/pages/func/timetable/pages/editor/index",
  CLASSROOM: "/pages/func/classroom/index",
  GRADE: "/pages/func/grade/index",
  SHARE_TABLE: "/pages/func/share-table/index",
  PLUS: "/pages/plus/index/index",
  USER: "/pages/user/index/index",
  POST: "/pages/user/post/index",
  NOT_FOUNT: "/pages/app/404/index",
  WEBVIEW: "/pages/app/webview/index",
};
